using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoeStore.Models
{
    public class Shoe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string ReleaseMonth { get; set; }
        public string ImageName { get; set; }


        #region Static Values
        private static List<Shoe> shoes;
        static Shoe()
        {
            // Default Temp Shoe values
            shoes = new List<Shoe>();
            shoes.Add(new Shoe() { Id = 1, Name = "Jimmy Choo Kendall Crystal Pump", Brand = "Jimmy Choo", Price = 2995, Description = "A scintillating mix of crystals casts flashbulb dazzle across a red carpet–ready pump, perched atop a slim heel. Jimmy Choo Kendall Crystal Pump Jimmy Choo Jimmy Choo Pumps Shoes Approx. heel height: 5 3/4\" with 1 1/2\" platform (comparable to a 4 1/4\" heel). Measurements taken from size 39 EU and may vary slightly by size. Metallic leather upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "January", ImageName = "Jimmy_Choo_Kendall_Crystal_Pump.jpg" });
            shoes.Add(new Shoe() { Id = 2, Name = "Brian Atwood Tribeca Laser Sandal", Brand = "Brian Atwood", Price = 1695, Description = "Diminutive studs trace the intricate waves of a sky-high, summer-breeze sandal. Brian Atwood Tribeca Laser Sandal BRIAN ATWOOD Brian Atwood Sandals/Slides Shoes Approx. heel height: 6\" with 1 1/2\" platform (comparable to a 4 1/2\" heel). Suede upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "January", ImageName = "Brian_Atwood_Tribeca_Laser_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 3, Name = "Sergio Rossi Mermaid Caged Sandal", Brand = "BrianSergio Rossi", Price = 1670, Description = "Suede waves dotted with Swarovski crystals create an airy sandal lifted by a super-slim wrapped heel. Sergio Rossi Mermaid Caged Sandal SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Back zip closure. Approx. heel height: 4\". Suede, satin and Swarovski crystal upper/leather lining and sole. Imported. Salon Shoes.", ReleaseMonth = "January", ImageName = "Sergio_Rossi_Mermaid_Caged_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 4, Name = "Charlotte Olympia Priscilla Genuine Python Pump", Brand = "Charlotte Olympia", Price = 1495, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.Exotic python and exuberant emerald take a signature pump to exhilarating heights of style. Charlotte Olympia Priscilla Genuine Python Pump CHARLOTTE OLYMPIA Charlotte Olympia Pumps Shoes Approx. heel height: 5 3/4\" with 1 1/2\" platform (comparable to a 4 1/4\" heel). Genuine python upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "January", ImageName = "Charlotte_Olympia_Priscilla_Genuine_Python_Pump.jpg" });
            shoes.Add(new Shoe() { Id = 5, Name = "Jimmy Choo Diva Sandal", Brand = "Jimmy Choo", Price = 1495, Description = "Scintillating architecture and precision-set crystals create captivating after-dark sparkle on a cut-out, champagne sandal. Jimmy Choo Diva Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Back zip closure. Approx. heel height: 5\" with 3/4\" platform. Leather upper, lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "January", ImageName = "Jimmy_Choo_Diva_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 6, Name = "Jimmy Choo Kera Platform Sandal", Brand = "Jimmy Choo", Price = 2195, Description = "Brilliant crystals dazzle the T-strap style of a scintillating platform sandal balanced by a slim, wrapped heel. Jimmy Choo Kera Platform Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Approx. heel height: 4 1/4\" with 1/2\" platform. Measurements taken from size 39 EU and may vary slightly by size. Back zip closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "February", ImageName = "Jimmy_Choo_Kera_Platform_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 7, Name = "Valentino Camo Rockstud Pump", Brand = "Valentino", Price = 1595, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.Golden pyramid studs glint on the caged straps of a crystallized leather pump with a slim heel and pointed toe. Valentino Camo Rockstud Pump VALENTINO Valentino Pumps Shoes Approx. heel height: 4\". Adjustable strap with buckle closure. Leather upper, lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "February", ImageName = "Valentino_Camo_Rockstud_Pump.jpg" });
            shoes.Add(new Shoe() { Id = 8, Name = "Miu Miu Ankle Strap Platform Sandal", Brand = "Miu Miu", Price = 1495, Description = "Miu Miu Ankle Strap Platform Sandal MIU MIU Miu Miu Sandals/Slides Shoes Adjustable strap with buckle closure. Approx. heel height: 5 1/4\" with 1 3/4\" platform (comparable to a 3 1/2\" heel). Metallic leather upper/leather lining/rubber sole. Made in Italy. Salon Shoes.", ReleaseMonth = "March", ImageName = "Miu_Miu_Ankle_Strap_Platform_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 9, Name = "Valentino Camo Rockstud Flat", Brand = "Valentino", Price = 1595, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.Pyramid studs amp up the edgy vibe of a pointy flat aglow with glittering crystals. Valentino Camo Rockstud Flat VALENTINO Valentino Flats Shoes Leather upper, lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "March", ImageName = "Valentino_Camo_Rockstud_Flat.jpg" });
            shoes.Add(new Shoe() { Id = 10, Name = "Jimmy Choo Kalpa Sandal", Brand = "Jimmy Choo", Price = 1495, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.Diminutive crystals trace the elegant lines of a plush suede sandal topped with a lofty, ankle-wrap strap. Jimmy Choo Kalpa Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Approx. heel height: 5 1/2\" with 1 1/2\" platform (comparable to a 4\" heel). Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "April", ImageName = "Jimmy_Choo_Kalpa_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 11, Name = "Sergio Rossi Murmansk Sandal", Brand = "Sergio Rossi", Price = 1495, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.Midnight crystals and starlight sparkle mingle atop the impeccable architecture of a curvaceous sandal, balanced atop a slim, satin heel. Sergio Rossi Murmansk Sandal SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Approx. heel height: 4\". Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "April", ImageName = "Sergio_Rossi_Murmansk_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 12, Name = "Brian Atwood Maia Sandal", Brand = "Brian Atwood", Price = 1995, Description = "A radiant sculpture of mixed media creates a statement T-bar sandal balanced atop a slim heel and platform. Brian Atwood Maia Sandal BRIAN ATWOOD Brian Atwood Sandals/Slides Shoes Approx. heel height: 6\" with 1 1/2\" platform (comparable to a 4 1/2\" heel). Leather and genuine stingray upper/leather lining and sole. Salon Shoes. Made in Italy.", ReleaseMonth = "May", ImageName = "Brian_Atwood_Maia_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 13, Name = "Lanvin Lucite® Wedge Sandal", Brand = "Lanvin", Price = 1590, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.A contemporary slice of Lucite® heightens the modern appeal of a scalloped suede sandal for head-turning impact. Lanvin Lucite® Wedge Sandal LANVIN Lanvin Sandals/Slides Shoes Adjustable strap with buckle closure. Suede upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "May", ImageName = "Lanvin_Lucite_Wedge_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 14, Name = "Old Gringo Diego Swarovski Boot", Brand = "Old Gringo", Price = 1889.95, Description = "Swarovski crystals trace a sparkling pattern on a Western-style boot handcrafted in antiqued leather. Old Gringo Diego Swarovski Boot OLD GRINGO Old Gringo Boots Shoes Approx. heel height: 2. Approx. boot shaft height: 12 1/2\"; 15\" calf circumference. Leather upper, lining and sole. By Old Gringo; imported. BP. Shoes.", ReleaseMonth = "June", ImageName = "Old_Gringo_Diego_Swarovski_Boot.jpg" });
            shoes.Add(new Shoe() { Id = 15, Name = "Lanvin Pointy Toe Python Pump", Brand = "Lanvin", Price = 1550, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.High-impact iridescence ignites the razor-sharp silhouette of a hidden-platform pump perched on a sleek, silvery heel. Lanvin Pointy Toe Python Pump LANVIN Lanvin Pumps Shoes Approx. heel height: 5\" with 1\" platform (comparable to a 4\" heel). Adjustable strap with buckle closure. Genuine python upper/leather lining and sole. Imported. Salon Shoes", ReleaseMonth = "June", ImageName = "Lanvin_Pointy_Toe_Python_Pump.jpg" });
            shoes.Add(new Shoe() { Id = 16, Name = "Prada Crystal Platform Sandal", Brand = "Prada", Price = 1800, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships. Prada Crystal Platform Sandal Prada Prada Sandals/Slides Shoes Adjustable strap with buckle closure. Approx. heel height: 4 1/2\" with 1/2\" platform. Silk and crystal upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "July", ImageName = "Prada_Crystal_Platform_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 17, Name = "Lanvin Metal Heel Boot", Brand = "Lanvin", Price = 1550, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.A gilded heel elevates the structured personality of a prim platform boot with a chic pointy toe. Lanvin Metal Heel Boot LANVIN Lanvin Boots Shoes Approx. heel height: 5\" with 1\" platform (comparable to a 4\" heel). Side zip closure. Leather upper, lining and sole. Imported. Salon Shoes.", ReleaseMonth = "July", ImageName = "Lanvin_Metal_Heel_Boot.jpg" });
            shoes.Add(new Shoe() { Id = 18, Name = "Sergio Rossi Mermaid Bootie", Brand = "Sergio Rossi", Price = 1760, Description = "Metallic leather waves dotted with Swarovski crystals create an airy sandal lifted by a super-slim wrapped heel. Sergio Rossi Mermaid Bootie SERGIO ROSSI Sergio Rossi Sandals/Slides Shoes Back zip closure. Approx. heel height: 4\". Leather upper, lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "August", ImageName = "Sergio_Rossi_Mermaid_Bootie.jpg" });
            shoes.Add(new Shoe() { Id = 19, Name = "Gucci Noah Crystal dOrsay Pump", Brand = "Gucci", Price = 1495, Description = "Shimmering crystals illuminate a half dOrsay pump with black-tie refinement. Gucci Noah Crystal dOrsay Pump Gucci Gucci Pumps Shoes Approx. heel height: 4 1/4\". Satin upper/leather lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "August", ImageName = "Gucci_Noah_Crystal_dOrsay_Pump.jpg" });
            shoes.Add(new Shoe() { Id = 20, Name = "Prada Ankle Cuff Sandal", Brand = "Prada", Price = 1750, Description = "Prada Ankle Cuff Sandal Prada Prada Sandals/Slides Shoes Approx. heel height: 5 1/2\" with 1 3/4\" platform (comparable to a 3 3/4\" heel). Back zip closure with adjustable strap. Suede upper/leather lining and sole.", ReleaseMonth = "September", ImageName = "Prada_Ankle_Cuff_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 21, Name = "Old Gringo Eagle Swarovski Boot", Brand = "Old Gringo", Price = 1549.95, Description = "Swarovski crystals trace a sparkling pattern on a Western-style boot handcrafted in exceptionally soft leather. Old Gringo Eagle Swarovski Boot OLD GRINGO Old Gringo Boots Shoes Pull-on style. Approx. heel height: 1", ReleaseMonth = "September", ImageName = "Old_Gringo_Eagle_Swarovski_Boot.jpg" });
            shoes.Add(new Shoe() { Id = 22, Name = "Charlotte Olympia Cherie Sandal", Brand = "Charlotte Olympia", Price = 1695, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.A playful dose of je ne sais quoi charms a poodle-propped sandal cast in pale pink. Charlotte ", ReleaseMonth = "October", ImageName = "Charlotte_Olympia_Cherie_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 23, Name = "Jimmy Choo Kalpa Sandal", Brand = "Jimmy Choo", Price = 1495, Description = "Radiant snakeskin shimmers across the scintillating height of a fiercely feminine, ankle-strap sandal. Jimmy Choo Kalpa Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Adjustable strap with buckle closure. Leather upper, lining and sole. Made in Italy. Salon Shoes.", ReleaseMonth = "October", ImageName = "Jimmy_Choo_Kalpa_Sandal.jpg" });
            shoes.Add(new Shoe() { Id = 24, Name = "Charlotte Olympia Parisienne Sandal", Brand = "Charlotte Olympia", Price = 1495, Description = "Pre-order this style today! Add to Shopping Bag to view approximate ship date. Youll be charged only when your item ships.A lithe, ankle-wrap strap tops off the crystalline decadence of an ethereally translucent ", ReleaseMonth = "November", ImageName = "" });
            shoes.Add(new Shoe() { Id = 25, Name = "Jimmy Choo Lola Ankle Strap Sandal", Brand = "Jimmy Choo", Price = 1495, Description = "Fierce florals paint the exotic texture of a snakeskin sandal balanced atop a slim heel and generous platform. Jimmy Choo Lola Ankle Strap Sandal Jimmy Choo Jimmy Choo Sandals/Slides Shoes Adjustable strap with", ReleaseMonth = "November", ImageName = "" });
        }
        #endregion Static Values

        public static List<Shoe> GetAllShoes()
        {
            return shoes;
        }
    }
}
