using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoeStore.Models
{
    public class ShoeViewModel
    {
        public static SelectList ShoeBrand;
        static ShoeViewModel()
        {
            string[] shoeBrands = { "Select Brand",
                        "7 For All Mankind®",
                        "Acorn",
                        "Aetrex",
                        "Ahnu",
                        "Alegria",
                        "Alexander McQueen",
                        "Alexandre Birman",
                        "Alberto Fermani",
                        "Alberto Gozzi",
                        "Alice + Olivia",
                        "Andre Assous",
                        "Anyi Lu",
                        "ALDO",
                        "Aquatalia by Marvin K",
                        "Aravon",
                        "Arche",
                        "Ariat",
                        "Ash",
                        "ASICS®",
                        "Athena Alexander",
                        "Attilio Giusti Leombruni",
                        "B Brian Atwood",
                        "Badgley Mischka",
                        "BC Footwear",
                        "BCBGeneration",
                        "BCBGMAXAZRIA",
                        "Bed Stu",
                        "Bernardo",
                        "Betsey Johnson",
                        "Biala",
                        "Bionda Castana",
                        "Birkenstock",
                        "Birkis®",
                        "Blondo",
                        "Bogs",
                        "Børn",
                        "Boutique 9",
                        "BP.",
                        "Brian Atwood",
                        "Brooks",
                        "Burberry",
                        "Callisto",
                        "Calvin Klein",
                        "Charles by Charles David",
                        "Charlotte Olympia",
                        "Chinese Laundry",
                        "Chloé",
                        "Civic Duty",
                        "Clarks®",
                        "Classiques Entier®",
                        "COACH",
                        "Cobb Hill",
                        "Cole Haan",
                        "Converse",
                        "Cordani",
                        "Corso Como",
                        "Cushe",
                        "Dana Davis",
                        "Dansko",
                        "Delman",
                        "Dezario",
                        "Diane von Furstenberg",
                        "DKNYC",
                        "DolceGabbana",
                        "Dolce Vita",
                        "Donald J Pliner",
                        "Dr. Martens",
                        "DV by Dolce Vita",
                        "Earth®",
                        "Earthies®",
                        "ECCO",
                        "Eileen Fisher",
                        "Elie Tahari",
                        "Elizabeth and James",
                        "Emilio Pucci",
                        "Enzo Angiolini",
                        "Eric Michael",
                        "Ettore Masotti",
                        "Everybody",
                        "Fendi",
                        "Fergie",
                        "Fidji",
                        "Finn Comfort",
                        "FitFlop",
                        "Flounce",
                        "Franco Sarto",
                        "French Sole",
                        "Frye",
                        "Gentle Souls",
                        "Geox",
                        "Giuseppe Zanotti",
                        "Giesswein",
                        "Glint",
                        "Golden Goose",
                        "Gucci",
                        "GUESS",
                        "Haflinger",
                        "Halogen®",
                        "Havaianas",
                        "Helle Comfort",
                        "Helly Hansen",
                        "Hinge",
                        "House of Harlow 1960",
                        "Hunter",
                        "Icon Footwear",
                        "Isaac Mizrahi New York",
                        "Isola",
                        "Ivanka Trump",
                        "J. Reneé",
                        "Jack Rogers",
                        "Jacques Levine",
                        "Jambu",
                        "Jason Wu",
                        "Jeffrey Campbell",
                        "Jessica Simpson",
                        "Jimmy Choo",
                        "Joan  David",
                        "Joes",
                        "Josef Seibel",
                        "Juicy Couture",
                        "K Jacques St. Tropez",
                        "Kalso Earth®",
                        "Kamik",
                        "kate spade new york",
                        "Keds®",
                        "Keen",
                        "Kelsi Dagger",
                        "Kickers",
                        "Kork-Ease",
                        "KORS Michael Kors",
                        "L.A.M.B.",
                        "L.K. Bennett",
                        "La Canadienne",
                        "Lanvin",
                        "Le Chameau",
                        "Lucky Brand",
                        "Manolo Blahnik",
                        "MARC BY MARC JACOBS",
                        "Mark  James by Badgley Mischka",
                        "Martino",
                        "Matiko",
                        "Matisse",
                        "Matt Bernson",
                        "Me Too",
                        "Mel by Melissa",
                        "Mephisto",
                        "Merrell",
                        "MIA",
                        "MICHAEL Michael Kors",
                        "Minnetonka",
                        "Miss Trish",
                        "Miu Miu",
                        "Miz Mooz",
                        "Mizuno",
                        "MM6 Maison Martin Margiela",
                        "Moschino Cheap  Chic",
                        "Munro",
                        "N.Y.L.A.",
                        "Naot",
                        "Naturalizer",
                        "Naughty Monkey",
                        "Naya",
                        "Nelly Venturi",
                        "New Balance",
                        "Nicholas Kirkwood",
                        "Nike",
                        "Nina",
                        "Nine West",
                        "North Face",
                        "Old Gringo",
                        "OluKai",
                        "Onex",
                        "Oscar de la Renta",
                        "OTBT",
                        "Patagonia",
                        "Paul Green",
                        "Pedro Garcia",
                        "Pelle Moda",
                        "PIKOLINOS",
                        "Poetic Licence",
                        "Pollini",
                        "Pour la Victoire",
                        "Prada",
                        "PUMA",
                        "Rachel Roy",
                        "Rachel Zoe",
                        "rag  bone",
                        "Rainbow",
                        "Ralph Lauren Collection",
                        "Rebecca Minkoff",
                        "RED Valentino",
                        "Reed Krakoff",
                        "Reef",
                        "REPORT",
                        "Robert Clergerie",
                        "Robert Zur",
                        "Romika",
                        "Ron White",
                        "Rosegold",
                        "Roxy",
                        "Saint Laurent",
                        "Salvatore Ferragamo",
                        "Sam Edelman",
                        "Saucony",
                        "Sbicca",
                        "See by Chloé",
                        "Sergio Rossi",
                        "Seychelles",
                        "Skemo",
                        "Söfft",
                        "Softspots",
                        "SoftWalk®",
                        "Sole Goddess®",
                        "Sole Society",
                        "Sorel",
                        "Sperry Top-Sider®",
                        "Splendid",
                        "Stella McCartney",
                        "Steve Madden",
                        "Steven by Steve Madden",
                        "Stuart Weitzman",
                        "Superga",
                        "Sweet Ballerina",
                        "Tabitha Simmons",
                        "Taccetti",
                        "Tecnica®",
                        "Ted Baker London",
                        "Teva",
                        "The North Face",
                        "Tildon",
                        "Think!",
                        "Timberland",
                        "TKEES",
                        "Tods",
                        "TOMS",
                        "Topshop",
                        "Tory Burch",
                        "Tracy Reese",
                        "Trotters",
                        "Trouvé",
                        "Truth or Dare by Madonna",
                        "Tsubo",
                        "UGG® Australia",
                        "Valentino",
                        "VANELi",
                        "Vans",
                        "VC Signature",
                        "Vera Wang",
                        "Via Spiga",
                        "Vince",
                        "Vince Camuto",
                        "Yves Saint Laurent",
                        "Zadig  Voltaire"};
            ShoeBrand = new SelectList( shoeBrands.Select(x=> new{Text=x, Value=x}), "Value", "Text");
        }
    }
}